options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

steps:
  # reservations
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - us-east4-docker.pkg.dev/sleepr-458611/reservations/production
      - -f
      - apps/reservations/Dockerfile
      - apps/reservations
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - us-east4-docker.pkg.dev/sleepr-458611/reservations/production

  # payments
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - us-east4-docker.pkg.dev/sleepr-458611/payments/production
      - -f
      - apps/payments/Dockerfile
      - apps/payments
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - us-east4-docker.pkg.dev/sleepr-458611/payments/production
