apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservations
  labels:
    app: reservations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservations
  template:
    metadata:
      labels:
        app: reservations
    spec:
      containers:
      - name: reservations
        image: us-east4-docker.pkg.dev/sleepr-458611/reservations/production
        env:
          - name: MONGODB_URI
            value: "mongodb://mongodb-0.mongodb-headless:27017/sleepr"
          - name: HTTP_PORT
            value: "3000"
          - name: AUTH_HOST
            value: "auth"
          - name: AUTH_PORT
            value: "3001"
          - name: PAYMENT_HOST
            value: "payments"
          - name: PAYMENT_PORT
            value: "3003" 